name: lint
on: push
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        # https://github.com/bahmutov/npm-install
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint
